sugarcube-2:
  macros:
    dashline:
      name: dashline
    QuickStart:
      name: QuickStart
    StartBonus:
      name: StartBonus
    GameSetting:
      name: GameSetting
    CharaMaking:
      name: CharaMaking
    printmoney:
      name: printmoney
    notification:
      name: notification
    meterbar:
      name: meterbar
    you:
      name: you
    time:
      name: time
    fixvalue:
      name: fixvalue
    OverlayTitle:
      name: OverlayTitle
    status:
      name: status
    options:
      name: options
    saveList:
      name: saveList
    overlayReplace:
      name: overlayReplace
    timestats:
      name: timestats
    versioninfo:
      name: versioninfo
    variablesVersionUpdate:
      name: variablesVersionUpdate
    CMPenis:
      name: CMPenis
    CMVagina:
      name: CMVagina
    CMApply:
      name: CMApply
    CMMainclass:
      name: CMMainclass
    CMChara:
      name: CMChara
    CMGender:
      name: CMGender
    CMBodytype:
      name: CMBodytype
    CMSkin:
      name: CMSkin
    CMRace:
      name: CMRace
    CMHair:
      name: CMHair
    CMEyeColor:
      name: CMEyeColor
    CMButts:
      name: CMButts
    CMBreast:
      name: CMBreast
    CMHairColor:
      name: CMHairColor
    CMChest:
      name: CMChest
    CMMouth:
      name: CMMouth
    CMAnal:
      name: CMAnal
    CMBoy:
      name: CMBoy
    CMGirl:
      name: CMGirl
    CMChangeApply:
      name: CMChangeApply
    CMPsize:
      name: CMPsize
    showbasebar:
      name: showbasebar
    variablesStatic:
      name: variablesStatic
    DataBaseInstall:
      name: DataBaseInstall
    charainfo:
      name: charainfo
    changeinfo:
      name: changeinfo
    profile:
      name: profile
    hair:
      name: hair
    eye:
      name: eye
    skin:
      name: skin
    beauty:
      name: beauty
    lookbody:
      name: lookbody
    breast:
      name: breast
    lookhips:
      name: lookhips
    looktatoos:
      name: looktatoos
    skillrate:
      name: skillrate
    showschooldata:
      name: showschooldata
    displayskillrank:
      name: displayskillrank
    skillprocess:
      name: skillprocess
    showskilldata:
      name: showskilldata
    playerstatus:
      name: playerstatus
    clearAllWarning:
      name: clearAllWarning
    saveWarning:
      name: saveWarning
    loadWarning:
      name: loadWarning
    deleteWarning:
      name: deleteWarning
    CMBackground:
      name: CMBackground
    lang:
      name: lang
    printL:
      name: printL
    InitDataBase:
      name: InitDataBase
    InitGameData:
      name: InitGameData
    InitPlayerData:
      name: InitPlayerData
    InitNPCData:
      name: InitNPCData
    he:
      name: he
    showvaginity:
      name: showvaginity
    CMFurType:
      name: CMFurType
    GSApply:
      name: GSApply
    showwetness:
      name: showwetness
    setchara:
      name: setchara
    journal:
      name: journal
    socialmedia:
      name: socialmedia
    dictionary:
      name: dictionary
    achivement:
      name: achivement
    secretfile:
      name: secretfile
    statistics:
      name: statistics
    playrecord:
      name: playrecord
    items:
      name: items
    CMCri:
      name: CMCri
    sensitive:
      name: sensitive
    breast_info:
      name: breast_info
    penis:
      name: penis
    penis_info:
      name: penis_info
    vagina_info:
      name: vagina_info
    anal_info:
      name: anal_info
    ureth_info:
      name: ureth_info
    splits:
      name: splits
    genders:
      name: genders
    HoverTxt:
      name: HoverTxt
    hovertip:
      name: hovertip
      container: true
    icon:
      name: icon
    location:
      name: location
    call:
      name: call
    avatar:
      name: avatar
    InitAvatar:
      name: InitAvatar
    SetAvatar:
      name: SetAvatar
    InitClothUnderbottoms:
      name: InitClothUnderbottoms
    InitClothSocks:
      name: InitClothSocks
    InitClothShoes:
      name: InitClothShoes
    InitClothBottom:
      name: InitClothBottom
    InitClothTop:
      name: InitClothTop
    InitFace:
      name: InitFace
    checkimg:
      name: checkimg
    InitEmotion:
      name: InitEmotion
    setface:
      name: setface
    gonaked:
      name: gonaked
    CMEmote:
      name: CMEmote
    redress:
      name: redress
    setreveal:
      name: setreveal
    saveoutfit:
      name: saveoutfit
